#+title: E4 Toolbox - MATLAB para series temporales (UCM)
#+LANGUAGE: es
#+OPTIONS: title:nil toc:nil

# Metadatos SEO para Google y otros buscadores
#+HTML_HEAD: <meta name="description" content="E4 es una toolbox de MATLAB para modelización y análisis de series temporales mediante métodos de espacio de estados, desarrollada por el grupo EMLEC de la UCM.">
#+HTML_HEAD: <meta name="author" content="Grupo de Investigación UCM - Econometría, Machine Learning y Economía Computacional">
#+HTML_HEAD: <meta property="og:title" content="E4 Toolbox - MATLAB para series temporales (UCM)">
#+HTML_HEAD: <meta property="og:description" content="E4 es una toolbox de MATLAB para modelización y análisis de series temporales mediante métodos de espacio de estados, desarrollada por el grupo EMLEC de la UCM.">
#+HTML_HEAD: <meta property="og:type" content="website">
#+HTML_HEAD: <meta property="og:url" content="https://emlec-ucm.github.io/E4.html">
#+HTML_HEAD: <meta name="twitter:card" content="summary">
#+HTML_HEAD: <meta name="geo.region" content="ES-MD">
#+HTML_HEAD: <meta name="geo.placename" content="Madrid, España">
#+HTML_HEAD: <style>.sr-only { position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0,0,0,0); white-space:nowrap; }</style>

# Sin tema: esta página usa solo simple.css, más estrecha y con fondo oscuro si
# el sistema está en modo oscuro. Hay que enlazarla aquí porque las líneas
# HTML_HEAD de arriba sustituyen la cabecera por defecto de publish.el.
#+HTML_HEAD: <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css" />
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1.0">

#+BEGIN_EXPORT html
<h1 class="sr-only">E4 Toolbox - MATLAB para análisis de series temporales en espacio de estados (EMLEC - UCM)</h1>
#+END_EXPORT

/E4 es una toolbox de MATLAB, desarrollada por este grupo, para la modelización y el análisis de series temporales mediante métodos en el Espacio de los Estados. La documentación está en inglés./

* A MATLAB toolbox for time series analysis

** What is E4?

E4 is a MATLAB Toolbox for time series modeling and analysis. Its name, E4, refers to the Spanish /Estimación de modelos Econométricos en Espacio de los Estados/, meaning "State-Space Estimation of Econometric models".

E4 uses state-space methods to achieve flexibility and reliability. Although it is built on state-space methods, it also supports many standard time series models, such as VARMAX, structural econometric models, unobserved components, and many others.

The Toolbox also includes ready-to-use functions for model specification, preliminary parameter estimation, analytical computation of the likelihood gradient and the information matrix, simulation, forecasting, signal extraction, and more.

E4 is free software. You can download it from: [[https://www.ucm.es/e-4/]]

You are allowed to redistribute and/or modify E4 under the terms of the GNU General Public License (GPL) as published by the Free Software Foundation.

If you feel that our contribution deserves an acknowledgement, please cite the following book:

** Companion book

#+begin_quote
Jose Manuel Casals, Alfredo Garcia-Hiernaux, Miguel Jerez, Sonia Sotoca, Adao Alexandre Trindade: [[https://www.routledge.com/State-Space-Methods-for-Time-Series-Analysis-Theory-Applications-and-Software/Casals-Garcia-Hiernaux-Jerez-Sotoca-Trindade/p/book/9781482219593][State-Space Methods for Time Series Analysis. Theory, Applications and Software]]. CRC Press, 2016.
#+end_quote

See this book at [[https://www.routledge.com/State-Space-Methods-for-Time-Series-Analysis-Theory-Applications-and-Software/Casals-Garcia-Hiernaux-Jerez-Sotoca-Trindade/p/book/9781482219593][Routledge / CRC Press]], or download free supplementary materials from the [[https://www.ucm.es/e-4/ss-book-microsite][book microsite]].

[[https://www.ucm.es/e-4/ss-book-microsite][https://www.ucm.es/data/cont/docs/1034-2016-02-11-9781482219593.jpg]]
